{% set name = "exceptiongroup" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exceptiongroup-{{ version }}.tar.gz
  sha256: b241f5885f560bc56a59ee63ca4c6a8bfa46ae4ad651af316d4e81817bb9fd88

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - flit-scm
    - wheel
    - flit_scm
  run:
    - python
    - typing_extensions >=4.6.0  # [py<313]

test:
  imports:
    - exceptiongroup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/exceptiongroup/
  summary: Backport of PEP 654 (exception groups)
  description: |
    "This is a backport of the BaseExceptionGroup and ExceptionGroup classes from Python 3.11.
    It contains the following:
    * The exceptiongroup.BaseExceptionGroup and exceptiongroup.ExceptionGroup classes
    * A utility function (exceptiongroup.catch()) for catching exceptions possibly nested in an exception group
    * Patches to the TracebackException class that properly formats exception groups (installed on import)
    * An exception hook that handles formatting of exception groups through TracebackException (installed on import)
    * Special versions of some of the functions from the traceback module"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/agronholm/exceptiongroup
  doc_url: https://docs.python.org/3/library/exceptions.html

extra:
  recipe-maintainers:
    - xylar
